version: '3.1'

services:
    web:
        image: dorm-hub:latest
        restart: unless-stopped
        ports:
            - 13000:9000
        environment:
            - DB_HOST=host.docker.internal
            - DB_PORT=3306
            - DB_DATABASE=dorm-hub
            - DB_USERNAME=root
            - DB_PASSWORD=
        extra_hosts:
            - host.docker.internal:host-gateway
